### ISSUE TITLE
"Connecting..." indicator persists after a user clicks "Cancel" button

### ISSUE THREAD

**Issue by ukstv** [ceramicstudio/self.id#22]
https://user-images.githubusercontent.com/193527/118779909-2fb51800-b894-11eb-9386-946ac97f2625.mov

**Comment by PaulLeCam** [comment]
Seems to happen calling `did.authenticate()`, the promise stays in pending state.
Might need 3ID Connect to throw an error here?

**Comment by PaulLeCam** [comment]
@zachferland I've been looking into this, it seems the issue comes from the connect service in the iframe but doesn't get propagated to the DIDProviderProxy, so the promise just keeps hanging for any consumer.
I'm not really familiar with the iframe flows so I couldn't see an obvious way to address this, is this something you could have a look at please? Otherwise I'll dig more but might take some time to have a good solution.
